config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get 'how-search-works', to: 'static_pages#searchexplain'
  root 'beads#index'
  get '/beads', to: redirect("/")
  resources :beads

  # https://stackoverflow.com/a/18080494
  resources :contact_forms, path: "contact", as: :contact_forms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bead.rb
class Bead < ApplicationRecord

  include PgSearch::Model
    # search functionality adapted from
    # https://medium.com/swlh/advanced-filtering-for-your-rails-5-application-28c8da2d29b6
    pg_search_scope :category_search,
      against: [:brand, :size, :shape],
      associated_against: {
        colors: [:name]
      },
      using: {
        tsearch: {any_word: true}
      }

  # all image related functionality taken from
  # https://medium.com/@anaharris/how-to-add-image-upload-functionality-to-your-rails-app-9f7fc3f3d042
  has_one_attached :photo
  validates :brand, presence: true
  #validates :color, presence: true, length: {maximum: 32}
  acts_as_taggable_on :colors
  validates :size, presence: true, length: {maximum: 32}
  validates :shape, presence: true, length: {maximum: 32}
  validates :description, length: {maximum: 100000}

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Bead Listing - Contact Form",
      :to => "anknguyenanknguyen@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beads_controller.rb
class BeadsController < ApplicationController

  def new
    @bead = Bead.new
  end

  def create
    @bead = Bead.new(bead_params)
    if @bead.save
      redirect_to bead_url(@bead)
    else
      render 'new'
    end
  end

  def show
    @bead=Bead.find(params[:id])
  end

  def edit
    @bead = Bead.find(params[:id])
    render 'new'
  end

  def update
    @bead = Bead.find(params[:id])
    #@bead.photo.attach(params[:photo])
    @bead.update(bead_params)
    if @bead.save
      redirect_to bead_url(@bead)
    else
      render 'new'
    end
  end

  def destroy
    Bead.destroy(params[:id])
    redirect_to '/'
  end

  def index
      if params[:search]

        temp = Bead.all
        @colorfilter = params[:search][:colors].reject(&:blank?)
        if @colorfilter.any?
          temp = temp.category_search("#{@colorfilter}")
        end

        @brandfilter = params[:search][:brands].reject(&:blank?)
        if @brandfilter.any?
          temp = temp.category_search("#{@brandfilter}")
        end

        @sizefilter = params[:search][:sizes].reject(&:blank?)
        if @sizefilter.any?
          temp = temp.category_search("#{@sizefilter}")
        end

        @shapefilter = params[:search][:shapes].reject(&:blank?)
        if @shapefilter.any?
          temp = temp.category_search("#{@shapefilter}")
        end

        @beads = temp
      else
        @beads = Bead.all
      end
      respond_to do |format|
       format.html
       format.js
     end
  end

  private

    def bead_params
      params.require(:bead).permit(:brand,:color_list,:size,:shape,:description,:photo)
    end

end

app/controllers/contact_forms_controller.rb
# https://everydayrails.com/2011/09/07/rails-contact-form.html

class ContactFormsController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def create
    begin
      @contact_form = ContactForm.new(params[:contact_form])
      @contact_form.request = request
      if !@contact_form.deliver
        render 'new'
      end
    rescue ScriptError
      flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def searchexplain
    respond_to do |format|
     format.html
     format.js
   end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title="")
    base_title = "Bead Listing"
    if page_title.empty?
      return base_title
    else
      return page_title+" | "+base_title
    end
  end

end

app/helpers/beads_helper.rb
module BeadsHelper

# generates automatic dropdown options for new/edit page
# https://stackoverflow.com/a/50450751
# https://stackoverflow.com/a/4674091
def dropdown_generate(column_name)
  col =  Bead.order(updated_at: :desc).pluck(column_name).uniq
  content_tag :datalist, id: column_name do
    col.collect do |opt|
      concat(content_tag(:option, opt))
    end
  end
end

def dropdown_color_generate()
  col =  Bead.color_counts.pluck(:name).uniq.sort_by!{|e| e.downcase}
  content_tag :datalist, id: "color" do
    col.collect do |opt|
      concat(content_tag(:option, opt))
    end
  end
end

end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/beads/_addbead.html.erb
<%# render add bead tile %>
<div class = "bead" id = "add-bead-tile">
  <a id = "add-bead" href="/beads/new">
  <p>Add</p><p>New</p><p>Beads</p></a>
</div>

app/views/beads/_bead.html.erb
<%# render individual bead display %>

<div class = "bead" id = bead.id>
  <% if(bead.photo.attached?) %>
    <%= image_tag(bead.photo, class:"bead-photo") %>
  <% end %>
  <p> <span class = "underline">Brand:</span><span> </span>
      <%= bead.brand %> </p>
  <p> <span class = "underline">Color:</span><span> </span>
      <%= bead.color_list %> </p>
  <p> <span class = "underline">Size:</span><span> </span>
      <%= bead.size %> </p>
  <p> <span class = "underline">Shape:</span><span> </span>
      <%= bead.shape %> </p>
  <% if(descriptionInclude) %>
    <p> <span class = "underline">Description:</span><span> </span>
        <%= bead.description %> </p>
  <% end %>
  <div class = "bead-links">
    <%= link_to("Edit Bead", edit_bead_path(bead.id), \
           class: "bead-link" ) %>
   <span class = "link-divider"> | </span>
   <%= link_to("Delete Bead", bead_path(bead), method: :delete, \
          class: "bead-link", data: {confirm: "Are you sure you want to delete this bead?"} ) %>
  </div>
</div>

app/views/beads/_beads.html.erb
<%# render list of beads on the index %>

<% beads.each do |bead| %>
  <%= link_to(bead_path(bead.id), class: "bead-text") do %>
    <%= render 'bead', bead: bead, descriptionInclude: false %>
  <% end %>
<% end %>

app/views/beads/index.html.erb
<%#Creating advanced filtering
# https://medium.com/swlh/advanced-filtering-for-your-rails-5-application-28c8da2d29b6 %>
<div class = "index">

  <div class = "bead-search">

  <% @colors = Bead.color_counts.pluck(:name).uniq.sort_by!{|e| e.downcase}%>
  <% @brands = Bead.pluck(:brand).uniq.sort_by!{|e| e.downcase}%>
  <% @sizes = Bead.pluck(:size).uniq.sort_by!{|e| e.downcase}%>
  <% @shapes = Bead.pluck(:shape).uniq.sort_by!{|e| e.downcase}%>
  <%= simple_form_for :search, required: false, url: root_path, method: "GET", remote: true do |f| %>

  <h1>Search
    <%= link_to '?', "/how-search-works", {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', id: 'search-explain'} %>
  </h1>
    <div class="form-label" >Colors</div>
    <%= f.input :colors, label: false,  collection: @colors, as: :check_boxes %>

    <div class="form-label" >Brand</div>
    <%= f.input :brands, label: false,  collection: @brands, as: :check_boxes %>

    <div class="form-label" >Size</div>
    <%= f.input :sizes, label: false,  collection: @sizes, as: :check_boxes %>

    <div class="form-label" >Shape</div>
    <%= f.input :shapes, label: false,  collection: @shapes, as: :check_boxes %>

    <%= link_to "Reset Search", root_path, class: "btn button" %>
  <% end %>
  </div>

  <div class = "bead-list">

    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
      </div>
    </div>


    <%= render 'beads', beads: @beads %>
    <%= render 'addbead' %>
    <div class = "bead-placeholder"></div>
    <div class = "bead-placeholder"></div>
    <div class = "bead-placeholder"></div>
  </div>

</div>

<script type="text/javascript">
  var checkBoxes = document.getElementsByClassName("checkbox");
  var form = document.querySelector('form');

  for (const check of checkBoxes) {
  check.addEventListener( 'change', function() {
    Rails.fire(form, 'submit');
  });
  }
</script>

app/views/beads/index.js.erb
// https://medium.com/swlh/advanced-filtering-for-your-rails-5-application-28c8da2d29b6
function replaceBeads (innerHTML) {
  const beads = document.getElementsByClassName('bead-list')[0];
  let temp = innerHTML;
  temp += "<%= j render 'addbead' %>";
  for (let i = 0; i <3 ; i ++) {
      temp += "<div class = 'bead-placeholder'></div>";
  }
  beads.innerHTML = temp;
}

if ('<%= @filter %>' === "[]") {
replaceBeads("<%= j render 'beads', beads: Bead.all %>");
}
else {
replaceBeads("<%= j render 'beads', beads: @beads %>");
}

app/views/beads/new.html.erb
<%# configure correct title based on whether this is an add/edit %>
<% if action_name == "new" || action_name == "create" %>
  <% @newedit = "Add Bead" %>
  <% provide(:newedit, "Add Bead") %>
<% else %>
  <% @newedit = "Edit Bead" %>
  <% provide(:newedit, "Edit Bead") %>
<% end %>

<% provide(:title, @newedit ) %>

<%# generate  dropdown lists %>
<%= dropdown_generate(:brand) %>
<%= dropdown_color_generate %>
<%= dropdown_generate(:shape) %>
<%= dropdown_generate(:size) %>

<h1><%= yield :newedit %> </h1>
  <div class="d-flex align-content-center new-bead">
    <%= form_for @bead do |f| %>
    <%= render 'shared/error_messages', source: @bead %>

    <%= f.label :photo, class: "form-label" %>
    <%= f.file_field :photo, class: "form-control"%>

    <%= f.label :brand, class: "form-label" %>
    <input class='form-control' type="text" list="brand"
    name='bead[brand]' id = "bead_brand" value='<%=@bead.brand%>'>

    <%= f.label "Color (separate values with commas)", class: "form-label"  %>
    <input class='form-control' type="text" list="color"
    name='bead[color_list]' id = "bead_color" value='<%=@bead.color_list%>'>

    <%= f.label :size, class: "form-label"  %>
    <input class='form-control' type="text" list="size"
    name='bead[size]' id = "bead_size" value='<%=@bead.size%>'>

    <%= f.label :shape, class: "form-label"  %>
    <input class='form-control' type="text" list="shape"
    name='bead[shape]' id = "bead_shape" value='<%=@bead.shape%>'>

    <%= f.label :description, class: "form-label"  %>
    <%= f.text_area :description, size:"60x8", class:"form-control" %>
    <%= f.submit @newedit, class: "button form-control" %>
    <% end %>
  </div>

app/views/beads/show.html.erb
<% provide(:title) %>
<%= render 'bead', bead: @bead, descriptionInclude: true %>

app/views/contact_forms/create.html.erb
<%#app/views/contact_forms/create.html.erb %>
<h1>Thank you for your message!</h1>

I'll try to respond as soon as possible.

<div class = "bead">
<div class = "bead-links">
<%= link_to 'Main Page', root_url, class: 'bead-link' %>
</div>
</div>

app/views/contact_forms/new.html.erb
<%#app/views/contact_forms/new.html.erb %>
<% provide(:title, "Contact Me" ) %>
<h1>Contact Me</h1>

<p>Any feedback/suggestions/compliments? Leave them down below!</p>
<h1>FORM NOT ACTIVELY FUNCTIONAL.</h1>
<p>If you wish to contact me, please e-mail
  me at anguyen@hmc.edu.</p>
<div class="d-flex align-content-center new-bead">
<%= form_for @contact_form do |f| %>
  <%= render 'shared/error_messages', source: @contact_form %>

  <%= f.label :name, class: "form-label" %>
  <%= f. text_field :name, class: "form-control" %>

  <%= f.label :email, class: "form-label" %>
  <%= f.email_field :email, class: "form-control"  %>

  <%= f.label :message, class: "form-label" %>
  <%= f.text_area :message, size: "60x8", class:"form-control" %>

  <%= f.hidden_field :nickname %>

  <%= f.button "Send Message", class: "button form-control" %>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer page-footer d-flex justify-content-between mt-5">
  <div class="footer-text">
    <br>
    Created by An Nguyen during CS189: Programming Practicum (Spring 2020) at Harvey Mudd College.
  </div>
  <div class="github-link">
    <a href="https://github.com/nguyenank/bead-listing">
    <%= image_tag("GitHub-Mark-32px.png", :alt => "GitHub logo") %>
    </a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg header">
    <div class = "title">
      <a href="/">Bead Listing </a>
    </div>

  <div class="nav-item dropdown">
    <a class="nav-link menu" href="#" id="navbarDropdown"
              role = "button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      ☰
    </a>
    <div class="dropdown-menu dropdown-menu-right dd" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="/beads/new">Add Beads</a>
      <a class="dropdown-item" href="/about">About</a>
      <a class="dropdown-item" href="/contact/new">Contact Me</a>
    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex-column">
    <%= render 'layouts/header' %>
    <div class="content">
      <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
     <%#= debug(params)  %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<%# Ruby on Rails Tutorial, error message%>
<% if source.errors.any? %>
    <div class="error-explanation">
      <div class="error-header">
        This form contains <%= pluralize(source.errors.count, "error") %>.
      </div>
      <ul>
      <% source.errors.full_messages.each do |msg| %>
        <li><%= msg +"." %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_searchexplain.html.erb
<%# link for modal creation: https://dzone.com/articles/rails-creating-modals %>

<div class="modal-header">
    <h1>How Search Works</h1>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p>
  Searching will display all beads fitting any option selected within a certain
  category. For example, selecting <span class = "option">red</span> and <span class = "option">blue</span> in the <span class = "form-label">Color</span> category will display
  all beads that are <span class = "option">red</span> <span class = "logic">or</span> <span class = "option">blue</span>.
</p>
<p>
  However if options are selected in multiple categories,
  only beads that fit a selected option from each category will be shown. For example, if <span class = "option">red</span> and <span class = "option">blue</span> are selected in <span class = "form-label">Color</span>, and
  <span class = "option">10mm</span> is selected in <span class = "form-label">Size</span>, then the application will display only beads that are <span class = "option">red</span> <span class = "logic">and</span> <span class = "option">10mm</span>, <span class = "logic">or</span> beads
   that are <span class = "option">blue</span> <span class = "logic">and</span> <span class = "option">10mm</span>.
 </p>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

<p>This is a web application that allows you to keep track of beads you own. You can specify the brand, color, shape, size and add a description, as well as sort through them.</p>
<p>It was built using Rails.</p>

app/views/static_pages/searchexplain.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'searchexplain') %>");
$("#modal-window").modal();